FROM python:3.12-slim AS mybuild

#  Ваш код здесь #
WORKDIR /build

# только зависимости — чтобы кэш не сбрасывался при изменениях main.py
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.12-slim AS app

# чтобы не запускать от рута
RUN useradd -m -u 1000 appuser

# папка приложения
WORKDIR /app

# собранные зависимости
COPY --from=mybuild /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=mybuild /usr/local/bin /usr/local/bin

# само приложение код которого часто меняется
COPY main.py .

# исправили права
RUN chown -R appuser:appuser /app
USER appuser

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]